# Configuración mínima para GitHub Pages + Jekyll
title: NFC Andina
# Public GitHub Pages URL (sin basepath)
url: "https://pinnovacionalico.github.io"
# Base path del proyecto (repositorio). GitHub Pages publicará el sitio en
# https://pinnovacionalico.github.io/NFC_Andina/, por eso baseurl debe ser "/NFC_Andina"
baseurl: "/NFC_Andina"

authors: []

collections:
  people:
    output: true

permalink: /:collection/:name/

# Puedes añadir más opciones (theme, plugins) si vas a compilar con Actions
